# version: "3"

networks:
  onstock:

services:
  # Контейнер с базой данных
  db:
    container_name: db
    image: "postgres:14.9-alpine"
    restart: always
    ports:
         - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  database:

