name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: echo "$(pwd)"
      - name: Preserve .env
        run: |
          cp .env ../.env.bak || echo "No existing .env"
      - run: npm ci
      - run: npm run build --if-present
      - name: Restore .env
        run: |
          mv ../.env.bak .env || echo "No .env to restore"
      - run: pm2 restart 4
