name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        

    steps:
      - run: echo "$(pwd)"
      # - run: |
            # cp .env ../.env.bak || echo "No existing .env"
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: Restore .env
        run: |
          copy /home/admin2/secrets/.env.next .env.production || echo "No .env.production to copy"
      - run: npm run build --if-present
      - run: pm2 restart 6

      #  ../actions-runner-next/onStockClient/onstock-client/onstock-client/.env /home/admin2/secrets/env.next