name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - run: echo "$(pwd)"
      - uses: actions/checkout@v4

      # Кэширование npm и Next.js
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules/.cache
          key: npm-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-${{ matrix.node-version }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            echo "Found package-lock.json, installing dependencies..."
            rm -rf node_modules
            npm ci
          else
            echo "No package-lock.json found, skipping npm install"
          fi

      # Восстанавливаем .env
      - name: Restore .env
        run: |
          if [ -f /home/admin2/secrets/.env.production ]; then
            cp /home/admin2/secrets/.env.production .env.production
            echo ".env.production restored"
          else
            echo "No .env.production to copy"
          fi

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
            node_modules/.next/cache
          key: nextjs-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json', 'next.config.js') }}
          restore-keys: |
            nextjs-${{ runner.os }}-${{ matrix.node-version }}-

      - name: Build Next.js app
        run: npm run build --if-present

      - name: Restart PM2 process
        run: pm2 restart nextjs --update-env
